### ISSUE TITLE
make a new release?

### ISSUE THREAD

**Issue by bastelfreak** [agis/ruby-sdnotify#4]
Hi!
thanks for the awesome gem. I'm trying to package it for Arch Linux. Our packaging guidelines recommend to package the latest release and to run tests if they are available. I noticed that the last release of sdnotify does not contain tests, but master branch does. Would it be possible to get a new release/git tag with those tests? Can I somehow help to create a new release?

Cheers, Tim

**Comment by agis** [comment]
Hi @bastelfreak! Are you referring to a new gem archive that includes the test files? Or simply pushing a new release tag?

**Comment by bastelfreak** [comment]
Hi,
we build the package based on the git tag, so that would be fine already :)

**Comment by agis** [comment]
Cool! 0.1.1 released: https://github.com/agis/ruby-sdnotify/releases/tag/v0.1.1

**Comment by bastelfreak** [comment]
awesome, https://archlinux.org/packages/community/any/ruby-sd_notify/ is now in the repos and executes the tests during build!
